### ISSUE TITLE
User Interface Expansion: Deleting a spell (using standard SHIFT click) disables the spell/enchanted item search input

### ISSUE THREAD

**Issue by abitoftaste** [NullCascade/morrowind-mods#23]
Deleting a spell (using standard SHIFT click) disables the spell/enchanted item search input (until reload I think)

**Comment by Petethegoat** [comment]
https://github.com/MWSE/MWSE/issues/142

**Comment by Petethegoat** [comment]
https://github.com/MWSE/MWSE/commit/b01bf4318d961e22f3abc50e23a371fdf2796cfd
